[build]
  command = "npm install"
  functions = "functions" # Directory for Netlify Functions
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  from = "/*"
  to = "/index.html"
  status = 200